[build-system]
requires = [
    "scikit_build_core<0.3.0",
    "pybind11",
]
build-backend = "scikit_build_core.setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
